FROM golang:1.23.2-alpine3.20 AS builder


COPY . /src
RUN cd /src && go build -o /zdap-proxyd /src/cmd/zdap-proxyd/zdap-proxyd.go

FROM alpine:3.20.3
RUN apk add --no-cache tzdata ca-certificates
COPY --from=builder /zdap-proxyd /
CMD /zdap-proxyd